package Model;
// Generated Aug 7, 2019 9:04:54 AM by Hibernate Tools 4.3.1



/**
 * TbClasses generated by hbm2java
 */
public class TbClasses  implements java.io.Serializable {


     private Integer no;
     private String classId;
     private String className;

    public TbClasses() {
    }

    public TbClasses(String classId, String className) {
       this.classId = classId;
       this.className = className;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }




}


