package Model;
// Generated Aug 7, 2019 9:04:54 AM by Hibernate Tools 4.3.1



/**
 * TbScore generated by hbm2java
 */
public class TbScore  implements java.io.Serializable {


     private Integer no;
     private int studentId;
     private String fullname;
     private Float middleExam;
     private Float finalExam;
     private Float plusExam;
     private Float avgScore;

    public TbScore() {
    }

	
    public TbScore(int studentId) {
        this.studentId = studentId;
    }
    public TbScore(int studentId, String fullname, Float middleExam, Float finalExam, Float plusExam, Float avgScore) {
       this.studentId = studentId;
       this.fullname = fullname;
       this.middleExam = middleExam;
       this.finalExam = finalExam;
       this.plusExam = plusExam;
       this.avgScore = avgScore;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public Float getMiddleExam() {
        return this.middleExam;
    }
    
    public void setMiddleExam(Float middleExam) {
        this.middleExam = middleExam;
    }
    public Float getFinalExam() {
        return this.finalExam;
    }
    
    public void setFinalExam(Float finalExam) {
        this.finalExam = finalExam;
    }
    public Float getPlusExam() {
        return this.plusExam;
    }
    
    public void setPlusExam(Float plusExam) {
        this.plusExam = plusExam;
    }
    public Float getAvgScore() {
        return this.avgScore;
    }
    
    public void setAvgScore(Float avgScore) {
        this.avgScore = avgScore;
    }




}


