package Model;
// Generated Aug 15, 2019 4:13:09 PM by Hibernate Tools 4.3.1



/**
 * TbScore generated by hbm2java
 */
public class TbScore  implements java.io.Serializable {


    private Integer no;
    private String studentId;
    private String fullname;
    private Float middleExam;
    private Float finalExam;
    private Float plusExam;
    private Float avgScore;
    private String subjectId;

    public TbScore() {
    }

	
    public TbScore(String studentId) {
        this.studentId = studentId;
    }
    public TbScore(String studentId, String fullname, Float middleExam, Float finalExam, Float plusExam, Float avgScore, String subjectId) {
       this.studentId = studentId;
       this.fullname = fullname;
       this.middleExam = middleExam;
       this.finalExam = finalExam;
       this.plusExam = plusExam;
       this.avgScore = avgScore;
       this.subjectId = subjectId;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public Float getMiddleExam() {
        return this.middleExam;
    }
    
    public void setMiddleExam(Float middleExam) {
        this.middleExam = middleExam;
    }
    public Float getFinalExam() {
        return this.finalExam;
    }
    
    public void setFinalExam(Float finalExam) {
        this.finalExam = finalExam;
    }
    public Float getPlusExam() {
        return this.plusExam;
    }
    
    public void setPlusExam(Float plusExam) {
        this.plusExam = plusExam;
    }
    public Float getAvgScore() {
        return this.avgScore;
    }
    
    public void setAvgScore(Float avgScore) {
        this.avgScore = avgScore;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }




}


