package Model;
// Generated Aug 24, 2019 3:06:05 PM by Hibernate Tools 4.3.1



/**
 * TbSubject generated by hbm2java
 */
public class TbSubject  implements java.io.Serializable {


     private Integer no;
     private String subjectId;
     private String name;
     private String room;
     private String classId;

    public TbSubject() {
    }

    public TbSubject(String subjectId, String name, String room, String classId) {
       this.subjectId = subjectId;
       this.name = name;
       this.room = room;
       this.classId = classId;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }
    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }




}


