package Model;
// Generated Aug 9, 2019 2:11:40 PM by Hibernate Tools 4.3.1



/**
 * TbTimetable generated by hbm2java
 */
public class TbTimetable  implements java.io.Serializable {


     private Integer no;
     private Integer subjectId;
     private String subjectName;
     private Integer room;

    public TbTimetable() {
    }

    public TbTimetable(Integer subjectId, String subjectName, Integer room) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.room = room;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Integer getRoom() {
        return this.room;
    }
    
    public void setRoom(Integer room) {
        this.room = room;
    }




}


