package Model;
// Generated Aug 7, 2019 9:04:54 AM by Hibernate Tools 4.3.1



/**
 * TbTimetable generated by hbm2java
 */
public class TbTimetable  implements java.io.Serializable {


     private Integer no;
     private Integer subjectId;
     private Integer classId;
     private Integer studentId;

    public TbTimetable() {
    }

    public TbTimetable(Integer subjectId, Integer classId, Integer studentId) {
       this.subjectId = subjectId;
       this.classId = classId;
       this.studentId = studentId;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }




}


